version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      frontend-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    groups:
      rust-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    labels:
      - dependencies
