version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      frontend-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns:
          - "*"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
