import type { AgentRole, AppState, CommandPolicy, LoopStep, Provider, ProviderPreset } from "./types";

export const defaultProviders: Provider[] = [
  {
    id: "mock_adapter",
    name: "Mock Adapter",
    type: "mock",
    enabled: true,
    health: "ok",
    command: "",
    argsTemplate: "",
    versionArgs: "",
    promptMode: "stdin",
    runMode: "mock",
    timeoutSeconds: 15,
    maxOutputBytes: 50000,
    capabilities: ["plan", "write_code", "review_diff", "analyze_logs", "security_review", "structured_output"],
    assignedRoles: [],
    lastTestResult: "Built-in deterministic provider is available.",
  },
  {
    id: "codex_cli",
    name: "Codex CLI",
    type: "cli",
    enabled: true,
    health: "unknown",
    command: "codex",
    argsTemplate: 'exec --skip-git-repo-check --sandbox workspace-write --cd "{{cwd}}"',
    versionArgs: "--version",
    promptMode: "stdin",
    runMode: "mock",
    timeoutSeconds: 900,
    maxOutputBytes: 200000,
    capabilities: ["plan", "write_code", "generate_tests", "structured_output"],
    assignedRoles: ["lead", "developer", "product"],
  },
  {
    id: "claude_code",
    name: "Claude Code",
    type: "cli",
    enabled: true,
    health: "unknown",
    command: "claude",
    argsTemplate: "-p",
    versionArgs: "--version",
    promptMode: "stdin",
    runMode: "mock",
    timeoutSeconds: 900,
    maxOutputBytes: 200000,
    capabilities: ["review_diff", "analyze_logs", "security_review", "structured_output"],
    assignedRoles: ["architect", "qa", "reviewer", "security"],
  },
  {
    id: "local_terminal",
    name: "Local Terminal Runner",
    type: "local_runner",
    enabled: true,
    health: "ok",
    command: "",
    argsTemplate: "",
    versionArgs: "",
    promptMode: "stdin",
    runMode: "mock",
    timeoutSeconds: 300,
    maxOutputBytes: 200000,
    capabilities: ["run_build", "run_tests", "git_status", "git_diff"],
    assignedRoles: ["devops"],
    lastTestResult: "Local command runner is available in Tauri runtime.",
  },
];

export const defaultCommandPolicy: CommandPolicy = {
  allow: [
    "git status",
    "git diff",
    "pnpm build",
    "pnpm test",
    "pnpm lint",
    "npm run build",
    "npm test",
    "cargo test",
    "python -m pytest",
  ],
  approvalRequired: [
    "git push",
    "git reset --hard",
    "git clean",
    "deploy",
    "migration",
    "ssh",
    "scp",
    "kubectl",
    "terraform apply",
    "docker compose up",
    "docker run",
    "npm publish",
    "pnpm publish",
    "gh release",
    "curl",
    "wget",
    "brew install",
    "sudo",
    ".env",
  ],
  deny: ["rm -rf /", "mkfs", "dd if=", "diskutil erase", "format c:", "credential exfiltration", "private key", "write outside workspace"],
};

export const providerPresets: ProviderPreset[] = [
  {
    id: "codex_builder_claude_reviewer",
    name: "Codex Builder + Claude Reviewer",
    description: "Codex plans/writes, Claude reviews/security-checks, local runner executes build/test commands.",
    providers: defaultProviders,
  },
  {
    id: "local_safe_mock",
    name: "Local Safe Mock",
    description: "All agent providers stay in mock mode; only local runner can execute configured project checks.",
    providers: defaultProviders.map((provider) => ({
      ...provider,
      runMode: provider.type === "local_runner" ? "real" : "mock",
    })),
  },
  {
    id: "codex_only",
    name: "Codex Only",
    description: "Codex handles planning, implementation, review, security, and acceptance; useful before Claude is configured.",
    providers: defaultProviders.map((provider) =>
      provider.id === "codex_cli"
        ? {
            ...provider,
            assignedRoles: ["lead", "architect", "developer", "qa", "reviewer", "security", "product"],
          }
        : { ...provider, assignedRoles: provider.id === "local_terminal" ? ["devops"] : [] },
    ),
  },
];

export const defaultAgents: AgentRole[] = [
  {
    id: "lead",
    role: "Team Lead",
    mission: "Break down tasks, assign agents, and keep the loop bounded.",
    provider: "Codex CLI",
    providerId: "codex_cli",
    fallbackProviderIds: ["claude_code", "mock_adapter"],
    mode: "read_only",
    model: "codex",
    enabled: true,
    permissions: ["plan", "assign", "summarize"],
  },
  {
    id: "architect",
    role: "Architect",
    mission: "Protect system boundaries, data model, and integration contracts.",
    provider: "Claude Code",
    providerId: "claude_code",
    fallbackProviderIds: ["mock_adapter"],
    mode: "review_only",
    model: "claude",
    enabled: true,
    permissions: ["read", "design", "write_proposal"],
  },
  {
    id: "developer",
    role: "Developer",
    mission: "Implement approved changes on a task branch with tests.",
    provider: "Codex CLI",
    providerId: "codex_cli",
    fallbackProviderIds: ["mock_adapter"],
    mode: "write_workspace",
    model: "codex",
    enabled: true,
    permissions: ["read", "write_code", "run_safe_commands"],
  },
  {
    id: "qa",
    role: "QA",
    mission: "Run evidence-backed checks and block acceptance on failures.",
    provider: "Claude Code",
    providerId: "claude_code",
    fallbackProviderIds: ["mock_adapter"],
    mode: "review_only",
    model: "claude",
    enabled: true,
    permissions: ["run_tests", "collect_evidence"],
    localCommands: ["pnpm build"],
  },
  {
    id: "reviewer",
    role: "Reviewer",
    mission: "Review diffs, regressions, and acceptance criteria coverage.",
    provider: "Claude Code",
    providerId: "claude_code",
    fallbackProviderIds: ["mock_adapter"],
    mode: "review_only",
    model: "claude",
    enabled: true,
    permissions: ["read_diff", "review"],
  },
  {
    id: "security",
    role: "Security",
    mission: "Classify sensitive actions and scan for secrets or policy breaks.",
    provider: "Claude Code",
    providerId: "claude_code",
    fallbackProviderIds: ["mock_adapter"],
    mode: "read_only",
    model: "claude",
    enabled: true,
    permissions: ["read", "classify_command", "block"],
  },
  {
    id: "devops",
    role: "DevOps",
    mission: "Prepare build, CI, and deploy plans without unsafe execution.",
    provider: "Local Terminal Runner",
    providerId: "local_terminal",
    fallbackProviderIds: ["mock_adapter"],
    mode: "approval_required",
    model: "local",
    enabled: false,
    permissions: ["build", "prepare_deploy_plan"],
  },
  {
    id: "product",
    role: "Product Owner",
    mission: "Translate user intent into acceptance criteria and report outcomes.",
    provider: "Codex CLI",
    providerId: "codex_cli",
    fallbackProviderIds: ["claude_code", "mock_adapter"],
    mode: "read_only",
    model: "codex",
    enabled: true,
    permissions: ["write_criteria", "acceptance"],
  },
];

export const loopTemplate: LoopStep[] = [
  {
    id: "plan",
    state: "planned",
    agent: "Team Lead",
    roleId: "lead",
    providerId: "codex_cli",
    summary: "Task decomposed into bounded implementation steps.",
    evidence: "Plan artifact created with scope, risks, and stop conditions.",
    status: "waiting",
  },
  {
    id: "code",
    state: "coding",
    agent: "Developer",
    roleId: "developer",
    providerId: "codex_cli",
    summary: "Implementation patch prepared on a task branch.",
    evidence: "Changed files and generated tests attached to the loop.",
    status: "waiting",
  },
  {
    id: "build",
    state: "building",
    agent: "DevOps",
    roleId: "devops",
    providerId: "local_terminal",
    summary: "Build command discovered and executed in the project root.",
    evidence: "Build log captured with exit code and redacted output.",
    status: "waiting",
  },
  {
    id: "test",
    state: "testing",
    agent: "QA",
    roleId: "qa",
    providerId: "claude_code",
    summary: "Unit and smoke checks executed with evidence.",
    evidence: "Test summary contains command, duration, and pass/fail result.",
    status: "waiting",
  },
  {
    id: "review",
    state: "reviewing",
    agent: "Reviewer",
    roleId: "reviewer",
    providerId: "claude_code",
    summary: "Diff reviewed against acceptance criteria.",
    evidence: "Review report lists risks, missing tests, and unresolved items.",
    status: "waiting",
  },
  {
    id: "security",
    state: "security",
    agent: "Security",
    roleId: "security",
    providerId: "claude_code",
    summary: "Sensitive actions and secret leakage checks completed.",
    evidence: "Policy report classifies commands as allow, approval, or deny.",
    status: "waiting",
  },
  {
    id: "accept",
    state: "acceptance",
    agent: "Product Owner",
    roleId: "product",
    providerId: "codex_cli",
    summary: "Acceptance report generated from task evidence.",
    evidence: "Final report links task, diff summary, tests, risks, and cost.",
    status: "waiting",
  },
];

export const initialState: AppState = {
  projects: [
    {
      id: "dbc",
      name: "Dildin Build Control",
      path: "/Users/vitaliy/DEV/DBC desktop",
      branch: "main",
      stack: ["Tauri", "React", "TypeScript", "Rust", "SQLite"],
      changedFiles: 0,
      openTasks: 1,
      risk: "medium",
      cost: 3.74,
      latestLoop: "planned",
    },
  ],
  activeProjectId: "dbc",
  providers: defaultProviders,
  agents: defaultAgents,
  commandPolicy: defaultCommandPolicy,
  tasks: [
    {
      id: "TASK-001",
      title: "Build MVP control loop shell",
      brief:
        "Create the local-first DBC desktop foundation with projects, task composer, AI team roles, loop monitor, approvals, audit, memory, and reports.",
      criteria: [
        "User can see project health and active loop status.",
        "User can create a task with acceptance criteria and budget.",
        "Mock loop runs plan -> code -> build/test -> review -> security -> acceptance.",
        "Sensitive actions appear in Approval Center and are recorded in audit.",
        "Final report is evidence-backed and cannot pass without checks.",
      ],
      constraints: ["Local-first data", "No destructive command execution", "Mock provider available by default"],
      budgetLimit: 10,
      risk: "medium",
      priority: "high",
      loopProfile: "mock",
      providerStrategy: "codex_build_claude_review",
      affectedPaths: ["src", "src-tauri", "README.md"],
      allowedPaths: ["src", "src-tauri", "README.md", ".dbc"],
      deniedPaths: [".env", "node_modules", "src-tauri/target"],
      requiredReviewers: ["Reviewer", "Security", "Product Owner"],
      stopConditions: [
        "Stop if a command is denied by policy.",
        "Stop if a change touches files outside the task scope.",
        "Stop if acceptance evidence is missing.",
      ],
      status: "ready",
    },
  ],
  loopSteps: loopTemplate,
  approvals: [
    {
      id: "APR-001",
      action: "git push origin dbc/task-001",
      reason: "Publishing code outside the local workspace is a sensitive action.",
      requester: "DevOps",
      risk: "high",
      preview: "Command is blocked until explicit approval. Branch contains generated MVP shell changes.",
      status: "pending",
    },
  ],
  audit: [
    {
      id: "AUD-001",
      time: "09:42",
      actor: "System",
      action: "Workspace initialized",
      result: "Project memory and mock provider templates created.",
    },
    {
      id: "AUD-002",
      time: "09:45",
      actor: "Security",
      action: "Classified git push",
      result: "Approval required by outbound code policy.",
    },
  ],
  costs: [
    {
      id: "COST-001",
      provider: "Mock Adapter",
      model: "dbc-planner",
      agent: "Team Lead",
      taskId: "TASK-001",
      amount: 0.84,
      confidence: "estimated",
    },
    {
      id: "COST-002",
      provider: "Mock Adapter",
      model: "dbc-coder",
      agent: "Developer",
      taskId: "TASK-001",
      amount: 2.9,
      confidence: "estimated",
    },
  ],
  memory: [
    {
      id: "MEM-001",
      type: "decision",
      title: "MVP stays local-first",
      body: "Cloud sync, marketplace, and enterprise governance are deferred until the core loop is proven.",
      author: "Architect",
      createdAt: "2026-06-28",
    },
    {
      id: "MEM-002",
      type: "risk",
      title: "Dangerous commands require approval",
      body: "Deploy, migration, secret changes, git push, SSH, and destructive shell actions must pause the loop.",
      author: "Security",
      createdAt: "2026-06-28",
    },
  ],
};
